#!/bin/bash
status=$(ps -ef | grep '[w]aybar -c' | grep menu | awk '{print $2}')
statu2=$(ps -ef | grep '[r]ofi -show' | awk '{print $2}')
run=$(cat ~/.bash/tjawa)

menu() {
	if [ -n "$status" ]; then
		kill "$status" | kill "$statu2"
	else
		# waybar -c ~/.config/waybar/menu/config.jsonc | rofi -show drun #-s ~/.config/waybar/menu/style.css	
		rofi -show drun	| waybar -c ~/.config/waybar/menu/config.jsonc
	fi
}

menu
