#!/bin/bash
# App and keybinds

$main = SUPER # Windows / Command Key

$terminal = kitty
$filemanager = pcmanfm
$menu = ~/.bash/menu
$browser = firefox
$discord = discord

########################

bind = $main, T, exec, $terminal
bind = $main, Q, killactive,
bind = $main SHIFT, Delete, exit,
bind = $main, E, exec, $filemanager
bind = $main, W, togglefloating,
bind = $main, A, exec, $menu
bind = $main, P, pseudo,
bind = $main, J, togglesplit,
bind = $main, B, exec, $browser
bind = $main, D, exec, $discord
bind = $main, R, exec, ~/.bash/refresh
bind = ,INSERT, exec, hyprshot -m output -o ~/Pictures/screenshot
bind = $main, INSERT, exec, hyprshot -m window -o ~/Pictures/screenshot
bind = $main, N, exec, swaync-client -t
bind = $main, Space, exec, ~/.bash/bar

#########################

bind = $main, left, movefocus, l
bind = $main, right, movefocus, r
bind = $main, up, movefocus, u
bind = $main, down, movefocus, d

bind = $main, 1, workspace, 1
bind = $main, 2, workspace, 2
bind = $main, 3, workspace, 3
bind = $main, 4, workspace, 4
bind = $main, 5, workspace, 5
bind = $main, 6, workspace, 6
bind = $main, 7, workspace, 7
bind = $main, 8, workspace, 8
bind = $main, 9, workspace, 9
bind = $main, 0, workspace, 10

##########################

bind = $main SHIFT, 1, movetoworkspace, 1
bind = $main SHIFT, 2, movetoworkspace, 2
bind = $main SHIFT, 3, movetoworkspace, 3
bind = $main SHIFT, 4, movetoworkspace, 4
bind = $main SHIFT, 5, movetoworkspace, 5
bind = $main SHIFT, 6, movetoworkspace, 6
bind = $main SHIFT, 7, movetoworkspace, 7
bind = $main SHIFT, 8, movetoworkspace, 8
bind = $main SHIFT, 9, movetoworkspace, 9
bind = $main SHIFT, 0, movetoworkspace, 10

bind = $main, S, togglespecialworkspace, magic
bind = $main SHIFT, S, movetoworkspace, special:magic

bind = $main, mouse_down, workspace, e+1
bind = $main, mouse_up, workspace, e-1

############################

bindm = $main, mouse:272, movewindow
bindm = $main, mouse:273, resizewindow

############################

bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,F8, exec, brightnessctl s 5%+
bindel = ,F7, exec, brightnessctl s 5%- 

bindl = ,F12, exec, playerctl next
##bindl = ,F11, exec, playerctl play-pause
bindl = ,F10, exec, playerctl previous

#############################
