#!/bin/bash
# Style

general {
	gaps_in = 			  0
	gaps_out = 			  0

	border_size = 		  2

	col.active_border =   rgba(b4befeff)
	col.inactive_border = rgba(1e1e2eaa)

	resize_on_border = 	  false

	allow_tearing = 	  false

	layout =			  dwindle
}

decoration {
	rounding = 		   1

	active_opacity =   1.0
	inactive_opacity = 1.0

	blur {
		enabled = true
		size = 6
		passes = 3

		vibrancy = 0  #0.1696
	}
}

animations {
	enabled = true

	bezier = myBezier, 0.05, 0.9, 0.1, 1.05
	
	bezier = custom, 0.165, 0.84, 0.44, 1
	bezier = kastem, 0.86, 0, 0.07, 1
	bezier = kont, 0, 0.31, 0, 1
	
	bezier = mm1, 1, 0, 0, 1
	bezier = mm2, 0.9, 0, 0.1, 1
	bezier = mm3, 0.8, 0, 0.2, 1
	bezier = mm4, 0.7, 0, 0.3, 1
	bezier = mm5, 0.6, 0, 0.4, 1
	bezier = mm6, 0.5, 0, 0.5, 1

	bezier = mk, 1, 0, 0.6, 1
	bezier = km, 0.4, 0, 0, 1

	bezier = sh, 0.2, 0.77, 0.77, 0.2
	bezier = hh, 0.1, 1, 0.1, 1
	
	bezier = quad, 0.5, 1, 0.89, 1
	bezier = cubic, 0.33, 1, 0.68, 1
	bezier = quart, 0.25, 1, 0.5, 1
	bezier = quint, 0.22, 1, 0.36, 1
	bezier = expo, 0.16, 1, 0.3, 1
	bezier = circ, 0, 0.55, 0.45, 1 

	animation = windows, 1, 3, km, slide bottom
	animation = windowsOut, 1, 5, mm4, slide bottom
	animation = border, 1, 10, default
	animation = borderangle, 1, 10, default
	animation = fade, 1, 6, quart
	animation = workspaces, 1, 6, hh, slide
}

dwindle {
	pseudotile = true
	preserve_split = true
}
master {
	new_status = master
}

misc {
	force_default_wallpaper = 0
	disable_hyprland_logo = true
}
